### ISSUE TITLE
Flask fails to import "escape" from Jinja2

### ISSUE THREAD

**Issue by psharma04** [Cog-Creators/Red-Dashboard#71]
### What part of dashboard are you having an issue with?

Dashboard webserver

### What happened?
When running the `reddash` command, Python returns an error:
```Traceback (most recent call last):
  File "/usr/local/bin/reddash", line 5, in <module>
    from reddash.__main__ import main
  File "/usr/local/lib/python3.10/site-packages/reddash/__main__.py", line 7, in <module>
    from reddash.app import create_app
  File "/usr/local/lib/python3.10/site-packages/reddash/app/__init__.py", line 8, in <module>
    from flask import Flask, url_for, session, render_template
  File "/usr/local/lib/python3.10/site-packages/flask/__init__.py", line 14, in <module>
    from jinja2 import escape
ImportError: cannot import name 'escape' from 'jinja2' (/usr/local/lib/python3.10/site-packages/jinja2/__init__.py)
```

### What did you expect to happen?
The command should have returned the [interface described in the Docs](https://red-dashboard.readthedocs.io/en/latest/launching_guides/running_webserver_one_bot.html).

### What can we do to reproduce this?
Following the [Mac/Linux Installation Guide](https://red-dashboard.readthedocs.io/en/latest/installation_guides/mac_linux_installation.html) using Ubuntu 20.04:
1. `$ python3 -m venv ~/reddashenv`
2. `$ source ~/reddashenv/bin/activate`
3. `$ python -m pip install -U pip setuptools wheel`
4. `$ python -m pip install -U Red-Dashboard`
5. `$ reddash` returns the error from above.

Full install logs available here: https://hastebin.skyra.pw/xasonomuso.log

### What is your bot/webserver running on?
- **Operating system**: Ubuntu 20.04.4 LTS x86_64
- **Python version**: Python 3.8.10
- **Dashboard webserver version**: Red-Dashboard-0.1.7a0
- **Dashboard cog version**: N/A (webserver doesn't get far enough to connect to the cog)

### What are you having issues on?
- **Operating system**: Ubuntu 20.04.4 LTS x86_64
- **Browser**: N/A

**Comment by Bazimek** [comment]
Same for me.
